"""Export CircuitGraph to synthesisable HDL (Verilog / VHDL).

Emits the optimized gate DAG as structural RTL that maps directly
to FPGA LUT primitives.  Every node in the graph becomes a module
instantiation:

- **CONST** → wire assignment (constant bit pattern)
- **Arithmetic** (add, sub, mul, div) → IEEE-754 FPU modules (instantiate
  vendor float IP, or behavioral for simulation)
- **LUT** (silu, exp, rsqrt) → ROM / block-RAM lookup table
- **Reductions** (sum, max_reduce) → reduction tree
- **Wiring** (reshape, transpose, slice) → wire reordering (zero logic)

Pipeline registers are inserted at subgraph boundaries (configurable
pipeline depth).

Target platforms:
- Xilinx Alveo / Zynq (LUT6): uses BRAM18/36 for activation LUTs
- Intel/Altera Stratix / Cyclone (ALM): uses M20K for activation LUTs
- Lattice iCE40 via Yosys/nextpnr: uses SPRAM for activation LUTs

Usage::

    from kllm.hdl_export import export_verilog, export_vhdl
    export_verilog(graph, "output/circuit.v")
    export_vhdl(graph, "output/circuit.vhd")
"""

from __future__ import annotations

import os
from datetime import datetime

import numpy as np

from kllm.circuit_graph import CircuitGraph, Node, Op


class _StreamWriter:
    """Drop-in replacement for ``list`` that streams lines to a file.

    Helper functions use ``_L = lines.append``; by passing a
    _StreamWriter instead of a real list, every line goes straight
    to disk — no 4 GB string in memory.
    """

    def __init__(self, f) -> None:
        self._f = f

    def append(self, line: str) -> None:          # noqa: D401
        self._f.write(line)
        self._f.write("\n")


# ---------------------------------------------------------------
# Verilog emitter
# ---------------------------------------------------------------

def export_verilog(
    graph: CircuitGraph,
    path: str,
    module_name: str = "circuit_top",
    pipeline_depth: int = 0,
    float_width: int = 32,
) -> str:
    """Export a CircuitGraph to synthesisable Verilog.

    Parameters
    ----------
    graph : CircuitGraph
        The circuit to export (typically after optimize_graph).
    path : str
        Output .v file path.
    module_name : str
        Top-level module name.
    pipeline_depth : int
        Number of pipeline register stages to insert.
    float_width : int
        Bit width per float element (32 for float32).

    Returns
    -------
    str
        Output file path.
    """
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    _file = open(path, "w")
    lines = _StreamWriter(_file)
    _L = lines.append

    # Analyse graph
    inputs = [n for n in graph.nodes if n.op == Op.INPUT]
    consts = [n for n in graph.nodes if n.op == Op.CONST]
    outputs = _find_output_nodes(graph)

    _L(f"// Auto-generated by kllm hdl_export")
    _L(f"// Date: {datetime.now().isoformat()}")
    _L(f"// Nodes: {len(graph)}, Pipeline: {pipeline_depth}")
    _L(f"")
    _L(f"module {module_name} (")
    _L(f"    input  wire clk,")
    _L(f"    input  wire rst_n,")
    _L(f"    input  wire valid_in,")
    _L(f"    output wire valid_out,")

    # Input ports
    for i, node in enumerate(inputs):
        size = _tensor_bits(node, float_width)
        _L(f"    input  wire [{size - 1}:0] in_{node.id},  // {node.name}")

    # Output ports
    for i, node in enumerate(outputs):
        size = _tensor_bits(node, float_width)
        comma = "" if i == len(outputs) - 1 else ","
        _L(f"    output wire [{size - 1}:0] out_{node.id}{comma}  // {node.name}")

    _L(f");")
    _L(f"")

    # Constant wires
    for node in consts:
        size = _tensor_bits(node, float_width)
        hex_val = _const_to_hex(node, float_width)
        _L(f"    // {node.name or f'const_{node.id}'}")
        _L(f"    wire [{size - 1}:0] n_{node.id} = {size}'h{hex_val};")

    _L(f"")

    # Input wire aliases
    for node in inputs:
        size = _tensor_bits(node, float_width)
        _L(f"    wire [{size - 1}:0] n_{node.id} = in_{node.id};")

    _L(f"")

    # Process nodes in topological order
    order = graph.topological_order()
    pipeline_stage = 0
    nodes_per_stage = max(1, len(order) // max(pipeline_depth, 1))

    for idx, nid in enumerate(order):
        node = graph.nodes[nid]
        if node.op in (Op.CONST, Op.INPUT):
            continue

        # Pipeline register insertion
        if pipeline_depth > 0 and idx > 0 and idx % nodes_per_stage == 0:
            pipeline_stage += 1
            _L(f"")
            _L(f"    // --- Pipeline stage {pipeline_stage} ---")
            _L(f"    reg [{float_width - 1}:0] pipe_{pipeline_stage}_valid;")
            _L(f"    always @(posedge clk or negedge rst_n)")
            _L(f"        if (!rst_n) pipe_{pipeline_stage}_valid <= 0;")
            _L(f"        else pipe_{pipeline_stage}_valid <= 1;")

        _emit_node_verilog(lines, node, graph, float_width)

    _L(f"")

    # Output assignments
    for node in outputs:
        _L(f"    assign out_{node.id} = n_{node.id};")

    # Valid pipeline
    if pipeline_depth > 0:
        _L(f"    assign valid_out = pipe_{pipeline_stage}_valid;")
    else:
        _L(f"    assign valid_out = valid_in;")

    _L(f"")
    _L(f"endmodule")
    _L(f"")

    # Emit helper modules
    _emit_helper_modules(lines, graph, float_width)

    _file.close()
    return path


# ---------------------------------------------------------------
# VHDL emitter
# ---------------------------------------------------------------

def export_vhdl(
    graph: CircuitGraph,
    path: str,
    entity_name: str = "circuit_top",
    float_width: int = 32,
) -> str:
    """Export a CircuitGraph to synthesisable VHDL.

    Parameters
    ----------
    graph : CircuitGraph
        The circuit to export.
    path : str
        Output .vhd file path.
    entity_name : str
        Top-level entity name.
    float_width : int
        Bit width per float element.

    Returns
    -------
    str
        Output file path.
    """
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    _file = open(path, "w")
    lines = _StreamWriter(_file)
    _L = lines.append

    inputs = [n for n in graph.nodes if n.op == Op.INPUT]
    consts = [n for n in graph.nodes if n.op == Op.CONST]
    outputs = _find_output_nodes(graph)

    _L(f"-- Auto-generated by kllm hdl_export")
    _L(f"-- Date: {datetime.now().isoformat()}")
    _L(f"-- Nodes: {len(graph)}")
    _L(f"")
    _L(f"library IEEE;")
    _L(f"use IEEE.std_logic_1164.all;")
    _L(f"use IEEE.numeric_std.all;")
    _L(f"")
    _L(f"entity {entity_name} is")
    _L(f"    port (")
    _L(f"        clk      : in  std_logic;")
    _L(f"        rst_n    : in  std_logic;")
    _L(f"        valid_in : in  std_logic;")
    _L(f"        valid_out: out std_logic;")

    for node in inputs:
        size = _tensor_bits(node, float_width)
        _L(f"        in_{node.id} : in  std_logic_vector({size - 1} downto 0);  -- {node.name}")

    for i, node in enumerate(outputs):
        size = _tensor_bits(node, float_width)
        semi = "" if i == len(outputs) - 1 else ";"
        _L(f"        out_{node.id}: out std_logic_vector({size - 1} downto 0){semi}  -- {node.name}")

    _L(f"    );")
    _L(f"end entity {entity_name};")
    _L(f"")
    _L(f"architecture rtl of {entity_name} is")
    _L(f"")

    # Signal declarations
    for node in graph.nodes:
        if node.op in (Op.CONST, Op.INPUT):
            continue
        size = _tensor_bits(node, float_width)
        _L(f"    signal n_{node.id} : std_logic_vector({size - 1} downto 0);  -- {node.op.value}: {node.name}")

    for node in consts:
        size = _tensor_bits(node, float_width)
        _L(f"    constant n_{node.id} : std_logic_vector({size - 1} downto 0) := x\"{_const_to_hex(node, float_width)}\";")

    _L(f"")
    _L(f"begin")
    _L(f"")

    # Input aliases
    for node in inputs:
        _L(f"    n_{node.id} <= in_{node.id} after 1 ns;  -- {node.name}")

    _L(f"")

    # Process nodes
    for nid in graph.topological_order():
        node = graph.nodes[nid]
        if node.op in (Op.CONST, Op.INPUT):
            continue
        _emit_node_vhdl(lines, node, graph, float_width)

    _L(f"")

    # Output assignments
    for node in outputs:
        _L(f"    out_{node.id} <= n_{node.id};")

    _L(f"    valid_out <= valid_in;")
    _L(f"")
    _L(f"end architecture rtl;")

    _file.close()
    return path


# ---------------------------------------------------------------
# Testbench generator
# ---------------------------------------------------------------

def export_testbench(
    graph: CircuitGraph,
    path: str,
    values: dict[int, np.ndarray],
    module_name: str = "circuit_top",
    float_width: int = 32,
) -> str:
    """Generate a SystemVerilog testbench with golden values.

    Uses pre-computed node values (from the reference evaluator)
    as golden checks.

    Parameters
    ----------
    graph : CircuitGraph
        The circuit under test.
    path : str
        Output testbench file path.
    values : dict
        Node values from evaluate() — used as golden reference.
    module_name : str
        Name of the DUT module.
    float_width : int
        Bit width per float element.

    Returns
    -------
    str
        The generated testbench source code.
    """
    lines: list[str] = []
    _L = lines.append

    inputs = [n for n in graph.nodes if n.op == Op.INPUT]
    outputs = _find_output_nodes(graph)

    _L(f"// Auto-generated testbench for {module_name}")
    _L(f"`timescale 1ns / 1ps")
    _L(f"")
    _L(f"module tb_{module_name};")
    _L(f"    reg clk = 0;")
    _L(f"    reg rst_n = 0;")
    _L(f"    reg valid_in = 0;")
    _L(f"    wire valid_out;")

    for node in inputs:
        size = _tensor_bits(node, float_width)
        _L(f"    reg [{size - 1}:0] in_{node.id};")

    for node in outputs:
        size = _tensor_bits(node, float_width)
        _L(f"    wire [{size - 1}:0] out_{node.id};")

    _L(f"")
    _L(f"    // DUT instantiation")
    _L(f"    {module_name} dut (")
    _L(f"        .clk(clk), .rst_n(rst_n),")
    _L(f"        .valid_in(valid_in), .valid_out(valid_out),")
    for node in inputs:
        _L(f"        .in_{node.id}(in_{node.id}),")
    for i, node in enumerate(outputs):
        comma = "" if i == len(outputs) - 1 else ","
        _L(f"        .out_{node.id}(out_{node.id}){comma}")
    _L(f"    );")
    _L(f"")
    _L(f"    // Clock generation")
    _L(f"    always #5 clk = ~clk;")
    _L(f"")
    _L(f"    initial begin")
    _L(f"        rst_n = 0;")
    _L(f"        #20 rst_n = 1;")
    _L(f"        #10;")

    # Drive inputs
    for node in inputs:
        if node.id in values:
            hex_val = _array_to_hex(values[node.id], float_width)
            _L(f"        in_{node.id} = {_tensor_bits(node, float_width)}'h{hex_val};")

    _L(f"        valid_in = 1;")
    _L(f"        #10;")

    # Check outputs (combinational — results available after propagation)
    for node in outputs:
        if node.id in values:
            size = _tensor_bits(node, float_width)
            hex_val = _array_to_hex(values[node.id], float_width)
            _L(f"        // Check {node.name}")
            _L(f"        if (out_{node.id} !== {size}'h{hex_val})")
            _L(f"            $error(\"MISMATCH: out_{node.id} expected={size}'h{hex_val} got=%h\", out_{node.id});")
            _L(f"        else")
            _L(f"            $display(\"PASS: out_{node.id}\");")

    _L(f"")
    _L(f"        $display(\"All checks completed.\");")
    _L(f"        $finish;")
    _L(f"    end")
    _L(f"endmodule")

    source = "\n".join(lines)
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(source)

    return source


# ---------------------------------------------------------------
# Resource estimation
# ---------------------------------------------------------------

def estimate_resources(
    graph: CircuitGraph,
    target: str = "xilinx",
    float_width: int = 32,
) -> dict:
    """Estimate FPGA resource utilization.

    Parameters
    ----------
    graph : CircuitGraph
        The circuit to analyze.
    target : str
        Target platform: 'xilinx', 'intel', or 'lattice'.
    float_width : int
        Bit width per float.

    Returns
    -------
    dict with resource estimates:
        luts, ffs, brams, dsps, estimated_fmax_mhz
    """
    counts = graph.gate_count()

    # Rough estimates per op type
    lut_cost = {
        "add": 32, "sub": 32, "mul": 0, "div": 128,
        "neg": 1, "abs": 1, "square": 0,
        "max": 32, "cmp_le": 32, "mux": 32,
        "sum": 32, "max_reduce": 32, "mean": 64,
        "argmax": 48,
    }
    dsp_cost = {"mul": 4, "square": 4, "matmul": 0}
    bram_cost = {"lut": 1}  # activation LUT uses 1 BRAM18 per instance

    total_luts = 0
    total_dsps = 0
    total_brams = 0

    for node in graph.nodes:
        op = node.op.value
        total_luts += lut_cost.get(op, 0)
        total_dsps += dsp_cost.get(op, 0)
        total_brams += bram_cost.get(op, 0)

    # Matmul: each is M*K multiply-accumulate operations
    for node in graph.nodes:
        if node.op == Op.MATMUL:
            # Estimate: each MAC uses 4 DSPs for float32
            # Without shape info, estimate conservatively
            total_dsps += 4

    # FFs: rough estimate from pipeline depth + control
    total_ffs = total_luts // 2 + 16  # control logic

    # Frequency estimate (rough)
    max_depth = len(graph.topological_order())
    fmax = max(10, 400 / max(max_depth, 1) * 10)  # crude

    return {
        "luts": total_luts,
        "ffs": total_ffs,
        "brams": total_brams,
        "dsps": total_dsps,
        "total_nodes": len(graph),
        "gate_nodes": counts["gate"],
        "wire_nodes": counts["wire"],
        "estimated_fmax_mhz": round(fmax, 1),
        "target": target,
    }


# ---------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------

def _find_output_nodes(graph: CircuitGraph) -> list[Node]:
    """Find nodes that are not consumed by any other node (graph outputs)."""
    consumed: set[int] = set()
    for node in graph.nodes:
        consumed.update(node.inputs)

    outputs = [n for n in graph.nodes if n.id not in consumed
               and n.op != Op.CONST]
    if not outputs:
        # Fallback: use the last node
        outputs = [graph.nodes[-1]] if graph.nodes else []
    return outputs


def _tensor_bits(node: Node, float_width: int) -> int:
    """Calculate total bits for a tensor node."""
    if node.op == Op.CONST and "value" in node.params:
        return max(1, node.params["value"].size * float_width)
    if node.shape:
        size = 1
        for s in node.shape:
            size *= s
        return max(1, size * float_width)
    return float_width  # default scalar


def _const_to_hex(node: Node, float_width: int) -> str:
    """Convert a CONST node's value to a hex string."""
    val = node.params.get("value")
    if val is None:
        return "0"
    return _array_to_hex(val, float_width)


def _array_to_hex(arr: np.ndarray, float_width: int) -> str:
    """Convert a numpy array to a hex string (MSB first)."""
    arr = np.ascontiguousarray(arr, dtype=np.float32)
    raw = arr.view(np.uint8)
    # Reverse byte order for Verilog (MSB first)
    hex_str = raw[::-1].tobytes().hex()
    return hex_str


def _emit_node_verilog(
    lines: list[str],
    node: Node,
    graph: CircuitGraph,
    float_width: int,
) -> None:
    """Emit Verilog for a single computation node."""
    _L = lines.append
    inputs_str = ", ".join(f"n_{i}" for i in node.inputs)

    if node.op in (Op.ADD, Op.SUB, Op.MUL, Op.DIV):
        op_sym = {Op.ADD: "+", Op.SUB: "-", Op.MUL: "*", Op.DIV: "/"}
        size = _tensor_bits(node, float_width)
        _L(f"    // {node.op.value}: {node.name}")
        _L(f"    wire [{size - 1}:0] n_{node.id};")
        _L(f"    fp_{node.op.value} #(.W({float_width})) u_{node.id} (")
        _L(f"        .a(n_{node.inputs[0]}), .b(n_{node.inputs[1]}), .y(n_{node.id})")
        _L(f"    );")

    elif node.op == Op.NEG:
        size = _tensor_bits(graph.nodes[node.inputs[0]], float_width)
        _L(f"    // neg: {node.name}")
        _L(f"    wire [{size - 1}:0] n_{node.id} = n_{node.inputs[0]} ^ {float_width}'h80000000;  // flip sign")

    elif node.op == Op.ABS:
        size = _tensor_bits(graph.nodes[node.inputs[0]], float_width)
        _L(f"    // abs: {node.name}")
        _L(f"    wire [{size - 1}:0] n_{node.id} = n_{node.inputs[0]} & {float_width}'h7FFFFFFF;  // clear sign")

    elif node.op == Op.SQUARE:
        size = _tensor_bits(node, float_width)
        _L(f"    // square: {node.name}")
        _L(f"    wire [{size - 1}:0] n_{node.id};")
        _L(f"    fp_mul #(.W({float_width})) u_{node.id} (")
        _L(f"        .a(n_{node.inputs[0]}), .b(n_{node.inputs[0]}), .y(n_{node.id})")
        _L(f"    );")

    elif node.op == Op.LUT:
        fn = node.params.get("fn", "unknown")
        size = _tensor_bits(graph.nodes[node.inputs[0]], float_width)
        _L(f"    // LUT ({fn}): {node.name}")
        _L(f"    wire [{size - 1}:0] n_{node.id};")
        _L(f"    lut_{fn} #(.W({float_width})) u_{node.id} (")
        _L(f"        .x(n_{node.inputs[0]}), .y(n_{node.id})")
        _L(f"    );")

    elif node.op == Op.MATMUL:
        size = _tensor_bits(node, float_width)
        _L(f"    // matmul: {node.name}")
        _L(f"    wire [{size - 1}:0] n_{node.id};")
        _L(f"    fp_matmul u_{node.id} (")
        _L(f"        .a(n_{node.inputs[0]}), .b(n_{node.inputs[1]}), .y(n_{node.id})")
        _L(f"    );")

    elif node.op == Op.MATMUL_Q8:
        size = _tensor_bits(node, float_width)
        _L(f"    // matmul_q8: {node.name}")
        _L(f"    wire [{size - 1}:0] n_{node.id};")
        _L(f"    fp_matmul_q8 u_{node.id} (")
        _L(f"        .x(n_{node.inputs[0]}), .w_q8(n_{node.inputs[1]}), .scales(n_{node.inputs[2]}), .y(n_{node.id})")
        _L(f"    );")

    elif node.op in (Op.MAX, Op.CMP_LE, Op.MUX):
        size = _tensor_bits(node, float_width)
        _L(f"    // {node.op.value}: {node.name}")
        _L(f"    wire [{size - 1}:0] n_{node.id};")
        _L(f"    fp_{node.op.value} #(.W({float_width})) u_{node.id} (")
        _L(f"        {inputs_str}, .y(n_{node.id})")
        _L(f"    );")

    elif node.op in (Op.SUM, Op.MAX_REDUCE, Op.MEAN, Op.ARGMAX):
        size = _tensor_bits(node, float_width)
        axis = node.params.get("axis", -1)
        _L(f"    // {node.op.value} axis={axis}: {node.name}")
        _L(f"    wire [{size - 1}:0] n_{node.id};")
        _L(f"    reduce_{node.op.value} #(.AXIS({axis})) u_{node.id} (")
        _L(f"        .x(n_{node.inputs[0]}), .y(n_{node.id})")
        _L(f"    );")

    elif node.op in (Op.RESHAPE, Op.TRANSPOSE, Op.CONCAT, Op.REPEAT,
                     Op.SLICE, Op.EXPAND_DIMS, Op.CAST):
        # Wire routing — synthesized as direct assignments
        _L(f"    // {node.op.value}: {node.name} (wire routing)")
        if node.inputs:
            _L(f"    wire [{_tensor_bits(node, float_width) - 1}:0] n_{node.id} = n_{node.inputs[0]};  // TODO: proper routing")
        else:
            _L(f"    wire [{float_width - 1}:0] n_{node.id} = 0;")

    else:
        _L(f"    // UNSUPPORTED: {node.op.value} {node.name}")
        _L(f"    wire [{float_width - 1}:0] n_{node.id} = 0;")


def _emit_node_vhdl(
    lines: list[str],
    node: Node,
    graph: CircuitGraph,
    float_width: int,
) -> None:
    """Emit VHDL for a single computation node."""
    _L = lines.append

    if node.op in (Op.ADD, Op.SUB, Op.MUL, Op.DIV):
        _L(f"    -- {node.op.value}: {node.name}")
        _L(f"    n_{node.id} <= fp_{node.op.value}(n_{node.inputs[0]}, n_{node.inputs[1]});")

    elif node.op == Op.NEG:
        _L(f"    -- neg: {node.name}")
        _L(f"    n_{node.id} <= n_{node.inputs[0]} xor x\"80000000\";")

    elif node.op == Op.ABS:
        _L(f"    -- abs: {node.name}")
        _L(f"    n_{node.id} <= n_{node.inputs[0]} and x\"7FFFFFFF\";")

    elif node.op == Op.LUT:
        fn = node.params.get("fn", "unknown")
        _L(f"    -- LUT ({fn}): {node.name}")
        _L(f"    n_{node.id} <= lut_{fn}(n_{node.inputs[0]});")

    elif node.op == Op.MATMUL:
        _L(f"    -- matmul: {node.name}")
        _L(f"    n_{node.id} <= fp_matmul(n_{node.inputs[0]}, n_{node.inputs[1]});")

    elif node.op == Op.MATMUL_Q8:
        _L(f"    -- matmul_q8: {node.name}")
        _L(f"    n_{node.id} <= fp_matmul_q8(n_{node.inputs[0]}, n_{node.inputs[1]}, n_{node.inputs[2]});")

    elif node.op in (Op.RESHAPE, Op.TRANSPOSE, Op.CONCAT, Op.REPEAT,
                     Op.SLICE, Op.EXPAND_DIMS, Op.CAST):
        _L(f"    -- {node.op.value}: {node.name} (wire routing)")
        if node.inputs:
            _L(f"    n_{node.id} <= n_{node.inputs[0]};  -- TODO: proper routing")

    else:
        _L(f"    -- {node.op.value}: {node.name}")
        if node.inputs:
            _L(f"    n_{node.id} <= n_{node.inputs[0]};  -- placeholder")


def _emit_helper_modules(
    lines: list[str],
    graph: CircuitGraph,
    float_width: int,
) -> None:
    """Emit behavioral Verilog helper modules for simulation.

    These are placeholder FPU modules.  For synthesis, replace with
    vendor IP (Xilinx Floating Point, Intel FP IP, etc.).
    """
    _L = lines.append
    ops_used = set()
    luts_used = set()

    for node in graph.nodes:
        if node.op in (Op.ADD, Op.SUB, Op.MUL, Op.DIV):
            ops_used.add(node.op.value)
        if node.op == Op.LUT:
            luts_used.add(node.params.get("fn", ""))

    if "matmul_q8" in {node.op.value for node in graph.nodes}:
        _L(f"")
        _L(f"// Behavioral INT8 matmul — replace with vendor IP for synthesis")
        _L(f"module fp_matmul_q8 (")
        _L(f"    input  wire [31:0] x,")
        _L(f"    input  wire [ 7:0] w_q8,")
        _L(f"    input  wire [31:0] scales,")
        _L(f"    output wire [31:0] y")
        _L(f");")
        _L(f"    // Behavioral: y = x * (float)w_q8 * scales")
        _L(f"    assign y = 32'b0;  // placeholder — implement as DSP MAC chain")
        _L(f"endmodule")

    for op in sorted(ops_used):
        op_sym = {"add": "+", "sub": "-", "mul": "*", "div": "/"}
        _L(f"")
        _L(f"// Behavioral float {op} — replace with vendor IP for synthesis")
        _L(f"module fp_{op} #(parameter W = 32) (")
        _L(f"    input  wire [W-1:0] a,")
        _L(f"    input  wire [W-1:0] b,")
        _L(f"    output reg  [W-1:0] y")
        _L(f");")
        _L(f"    shortreal a_f, b_f, y_f;")
        _L(f"    always @* begin")
        _L(f"        a_f = $bitstoshortreal(a);")
        _L(f"        b_f = $bitstoshortreal(b);")
        _L(f"        y_f = a_f {op_sym.get(op, '+')} b_f;")
        _L(f"        y = $shortrealtobits(y_f);")
        _L(f"    end")
        _L(f"endmodule")

    for fn in sorted(luts_used):
        if fn:
            _L(f"")
            _L(f"// LUT: {fn} — implement as BRAM ROM for synthesis")
            _L(f"module lut_{fn} #(parameter W = 32) (")
            _L(f"    input  wire [W-1:0] x,")
            _L(f"    output wire [W-1:0] y")
            _L(f");")
            _L(f"    // Placeholder — load ROM contents from activation mmap")
            _L(f"    assign y = x;  // identity for simulation skeleton")
            _L(f"endmodule")
